---
title: "tictactoe"
author: "JING LI"
date: "October 12, 2016"
output: html_document
---

```{r, error = TRUE}
# paste all of your code for this problem here
display <- function(state){
 cat(" ", state[1], "|", state[2],"|", state[3], "\n", "---+---+---\n ", state[4], "|", state[5], "|", state[6], "\n", "---+---+---\n ", state[7],"|", state[8],"|", state[9],"\n")
}
begin <- 1:9
```


```{r}
update <- function(state, who, pos){
  if(who != "x" && who !="o") {stop("Only x and o are allowed.\n")}
  if(is.numeric(pos)==FALSE) {stop("Only numbers 1 to 9 are allowed")}
  if(state[pos] == "x" || state[pos] == "o"){stop("The position has been taken")}
  else{state[pos]=who}
  
  return(state)
}
```

```{r}
computer_turn <- function(state){
if(length(which(state=="x")) < length(which(state=="o")))
if(state[5] !="x"&& state[5]!="o")pos <- 5
else if(state[1] !="x"&&state[1]!="o")pos <- 1
else if(state[3] !="x"&&state[3]!="o")pos <- 3
else if(state[7] !="x"&&state[7]!="o")pos <- 7
else if(state[9] !="x"&&state[9]!="o")pos <- 9
else if(state[2] !="x"&&state[2]!="o")pos <- 2
else if(state[4] !="x"&&state[4]!="o")pos <- 4
else if(state[6] !="x"&&state[6]!="o")pos <- 6
else if(state[8] !="x"&&state[8]!="o")pos <- 8

if(state[2]==state[3]|| state[4]==state[7]||state[5]==state[9])
     if(state[1] !="x"&&state[1]!="o")pos<-1
else if(state[1]==state[3]|| state[5]==state[8])
     if(state[2] !="x"&&state[2]!="o")pos<-2
else if(state[2]==state[1]|| state[5]==state[7]||state[6]==state[9])
     if(state[3] !="x"&&state[3]!="o")pos<-3
else if(state[1]==state[7]|| state[5]==state[6])
     if(state[4] !="x"&&state[4]!="o")pos<-4
else if(state[9]==state[1]||state[3]==state[7]||state[6]==state[4]||
    state[2]==state[8]) 
     if(state[5] !="x"&&state[5]!="o")pos<-5
else if(state[3]==state[9]|| state[5]==state[4])
     if(state[6] !="x"&&state[6]!="o")pos<-6
else if(state[4]==state[1]|| state[5]==state[3]||state[8]==state[9])
     if(state[7] !="x"&&state[7]!="o")pos<-7
else if(state[9]==state[7]|| state[5]==state[2])
     if(state[8] !="x"&&state[8]!="o")pos<-8
else if(state[5]==state[1]|| state[6]==state[3]||state[8]==state[7])
     if(state[9] !="x"&&state[9]!="o")pos<-9

  return(pos)
}
```


```{r}
user_turn <- function(state=begin,who="x"){
  cat(who, ",these are the available numbers:", state)
  pos <- readline("where do you want to play?\n")
  pos = as.integer(pos)
  return(pos)
}
```


```{r}
check_winner <- function(state=begin){
   result <- "no winner"
  if(all(state[c(1,2,3)]=="o")||all(state[c(4,5,6)]=="o")||all(state[c(7,8,9)]=="o")||
     all(state[c(1,4,7)]=="o")||all(state[c(2,5,8)]=="o")||all(state[c(3,6,9)]=="o")||
     all(state[c(1,5,9)]=="o")||all(state[c(3,5,7)]=="o"))result<-"o"
  if(all(state[c(1,2,3)]=="x")||all(state[c(4,5,6)]=="x")||all(state[c(7,8,9)]=="x")||
     all(state[c(1,4,7)]=="x")||all(state[c(2,5,8)]=="x")||all(state[c(3,6,9)]=="x")||
     all(state[c(1,5,9)]=="x")||all(state[c(3,5,7)]=="x"))result<-"x"
  if(all(state[1:9] %in% c("o","x")))result<-"tie"
  return(result)
}

```


```{r}
play <- function(){
  state =  begin
  display(state)
  player <- as.character((readline("How many players? Please answer 1 or 2.\n")))
  if(player == "1") {order <- as.character(readline("Do you want to go first or second? Please enter 1 or 2.\n"))}
  if(player == "2") order <- 1
  
 
for (i in 1:9) {
  
  if(i %% 2==1){
    who <- "x"
    if(player == "1" && order == "1"){
      pos <- user_turn(state, who)
      state <- update(state, who, pos)}
    if(player == "1" && order == "2"){
      pos <- computer_turn(state, who)
      state <- update(state, who, pos)}
    if(player == "2" && order == "1"){
      pos <- user_turn(state, who)
      state <- update(state, who, pos)}
  }
   if(i %% 2==0){
     who <- "o"
    if(player == "1" && order == "1"){
      pos <- computer_turn(state, who)
      state <-update(state, who, pos)}
    if(player == "1" && order == "2"){
      pos <- user_turn(state,who)
      state <- update(state, who, pos)}
    if(player == "2" && order == "1"){
      pos <- user_turn(state,who)
      state <- update(state, who, pos)}
   }
   
    display(state)
    check_winner(state)
    if(check_winner(state)=="no winner")i <- i+1
    if(check_winner(state)=="x"){print("x is winner!"): break}
    if(check_winner(state)=="o"){print("o is winner!"): break}
    if(check_winner(state)=="tie"){print("tie!"): break}
    
}
  
  
  # display final board state and who the winner is

}
```

```{r, error = TRUE}
teststate <- 1:9
display(teststate)
computer_turn(teststate)

teststate <- c("x", "2", "3", "4", "o", "x", "7", "o", "x")
display(teststate)
computer_turn(teststate)

teststate <- c("x", "x", "3", "o", "o", "6", "7", "o", "x")
display(teststate)
computer_turn(teststate)

teststate <- c("x", "2", "3", "4", "o", "x", "7", "o", "x")
newstate <- update(teststate, "o", 2)
display(newstate)

teststate <- c("x", "2", "3", "4", "o", "x", "7", "o", "x")
newstate <- update(teststate, "o", 1)

teststate <- c("x", "x", "3", "o", "o", "6", "7", "o", "x")
check_winner(teststate)

teststate <- c("x", "x", "x", "o", "o", "6", "7", "o", "x")
check_winner(teststate)

teststate <- c("x", "x", "o", "o", "o", "x", "x", "o", "x")
check_winner(teststate)
```

